### ISSUE TITLE
Fluxes definition

### ISSUE THREAD

**Issue by b-fg** [vavrines/FluxReconstruction.jl#6]
Hi,

I am having trouble finding the implementation of the fluxes definition as in: https://github.com/vavrines/FluxReconstruction.jl/blob/d79d3abd5b98878938e778f5285eb3476cce6d3a/example/euler_lowlevel.jl#L57
Could you please point me to it?

Thank you :)

**Comment by vavrines** [comment]
All fluxes are defined in [KitBase.jl](https://github.com/vavrines/KitBase.jl/blob/60306c04f73d30a833f9d157a0f513b75fdce8cf/src/Flux/flux_fluid.jl#L76)

**Comment by b-fg** [comment]
Noted, thanks!
